---
- hosts: all
  pre_tasks:
    - name: Ensure package database is up-to-date
      apt:
        update-cache: yes
      failed_when: false
      changed_when: false
      when: ansible_os_family == 'Debian'

  tasks:
  - include_role:
      name: bertvv.samba
    vars:
      samba_netbios_name: raspberrypi
      samba_workgroup: WORKGROUP

      samba_load_homes: true
      samba_load_printers: false
      samba_create_varwww_symlinks: false

      samba_log: /var/log/samba.log
      samba_log_size: 60000

      samba_map_to_guest: Never
      samba_users:
        - name: pi
          password: withicecream

      samba_shares_root: /mnt/usb
      samba_shares:
        - name: media
          valid_users: pi
          write_list: pi
          group: root
          comment: 'Media share'
  become: yes
  become_user: root
